print("Common String Methods in Python")
a="Hello, World!"
print("Original String:", a)
print("Uppercase:", a.upper())
print("Lowercase:", a.lower())
name="arjoo"
print(name.capitalize())  
print("Title Case:", a.title())
print(a.center(100))
print(a.count("l"))
print(a.casefold())
print(a.encode())
print(a.endswith("3"))
print(a.find("World"))
print(a.format())
print(a.format_map({"name": "arjoo"}))
print(a.index("o"))
print(a.isalnum())
print(a.isalpha())
print(a.isascii())
print(a.isdecimal())
print(a.isdigit())
print(a.isidentifier())
print(a.islower())
print(a.isnumeric())
print(a.isprintable())
print(a.isspace())
print(a.istitle())
print(a.isupper())
print(a.join(["I ", "am ", "New ", "To ", "Coding. "]))
print(a.ljust(50, '*'))
print(a.lstrip())
print(a.partition("World"))
print(a.replace("World", "Python"))
print(a.rfind("l"))
print(a.rindex("l"))
print(a.rjust(50, '*'))
print(a.rsplit(", "))
print(a.rstrip())
print(a.split(", "))
print(a.splitlines())
print(a.startswith("Hello"))
print(a.strip())
print(a.swapcase())
print(a.translate(str.maketrans("Helo", "1234")))
print(a.zfill(20))
print("String Length:", len(a))
print("String Reversed:", a[::-1])
print("String Split:", a.split())
print("String Join:", ", ".join(["Hello", "World"]))
print("String Comparison:", "Hello" == "hello")
print("String Concatenation:", "Hello" + " " + "World")
print("String Slicing:", a[0:5])  # Slicing the first 5 characters
print("String Indexing:", a[7])  # Accessing the character at index           